### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by kurak1n** [KarthikeyaEnge/StudyScraper_FrontEnd#3]
I'm new to this, how to download this app? because it looks like the main version was taken down😭

**Comment by KarthikeyaEnge** [comment]
just download the ver4 branch  and just install all the dependencies using ```npm install``` and then use the command ```npm run dev``` to start the frontend
- Note: This is just the frontend to use it download the backend and use same commands listed above

**Comment by kurak1n** [comment]
thanks!!
